# Form implementation generated from reading ui file 'item_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.nameEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.nameEdit.setGeometry(QtCore.QRect(10, 50, 113, 20))
        self.nameEdit.setObjectName("nameEdit")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 54, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(170, 20, 54, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(290, 20, 54, 16))
        self.label_3.setObjectName("label_3")
        self.categoryEdit = QtWidgets.QComboBox(parent=Dialog)
        self.categoryEdit.setGeometry(QtCore.QRect(160, 50, 68, 22))
        self.categoryEdit.setObjectName("categoryEdit")
        self.locationEdit = QtWidgets.QComboBox(parent=Dialog)
        self.locationEdit.setGeometry(QtCore.QRect(280, 50, 68, 22))
        self.locationEdit.setObjectName("locationEdit")
        self.descriptionEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.descriptionEdit.setGeometry(QtCore.QRect(150, 120, 104, 71))
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 90, 54, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(170, 90, 54, 16))
        self.label_5.setObjectName("label_5")
        self.quantitySpin = QtWidgets.QSpinBox(parent=Dialog)
        self.quantitySpin.setGeometry(QtCore.QRect(30, 130, 42, 22))
        self.quantitySpin.setObjectName("quantitySpin")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "名称"))
        self.label_2.setText(_translate("Dialog", "分类"))
        self.label_3.setText(_translate("Dialog", "位置"))
        self.label_4.setText(_translate("Dialog", "数量"))
        self.label_5.setText(_translate("Dialog", "描述"))
